version: 2
jobs:
  build:
    working_directory: ~/lufa-extension/
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: manifest version
          command: |
            sed -i 's/%VERSION%/$CIRCLE_TAG/g' src/manifest.json.tmpl > src/manifest.json
      - deploy:
          command: |
            sudo pip install requests && python deploy.py
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
                ignore: /.*/
