version: 2
jobs:
  build:
    working_directory: ~/lufa-extension/
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Package build
          command: |
            cd src && zip lufa-extension.zip ./*
      - run :
          name: Validate archive
          command: |
            zipinfo -1 lufa-extension.zip
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl \
              -H "Authorization: Bearer ${TOKEN}"  \
              -H "x-goog-api-version: 2" \
              -X PUT \
              -T lufa-extension.zip \
              -v \
              https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}
            fi
