version: 2
jobs:
  build:
    working_directory: ~/lufa-extension/
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: manifest version
          command: |
            sed -i 's/%VERSION%/$CIRCLE_TAG/g' src/manifest.json.tmpl > src/manifest.json
      - run:
          name: validate replace
          command: |
            cat src/manifest.json
      - run:
          name: Package build
          command: |
            cd src && zip -r lufa-extension.zip ./*
      - run :
          name: Validate archive
          command: |
            zipinfo -1 src/lufa-extension.zip
      - deploy:
          command: |
            pip install requests && python deploy.py
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
                ignore: /.*/
