version: 2
jobs:
  deploy:
    working_directory: ~/lufa-extension
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Package build
          command: |
            zip lufa-extension.zip src/*
      - run:
          name: Deploy to chrome store
          command: |
          curl \
            -H "Authorization: Bearer $TOKEN"  \
            -H "x-goog-api-version: 2" \
            -X PUT \
            -T lufa-extension.zip \
            -v \
            https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
